### ISSUE TITLE
Accident GPL Violation?

### ISSUE THREAD

**Issue by kawaii-ghost** [eraselk/ShellEncrypter-OSS#2]
Halo, saya sebagai pemilik repo
https://github.com/kawaii-ghost/deshc meminta anda untuk menyantumkan lisensi GPL V.3 ke dalam script yang sudah anda modifikasi.

**Comment by eraselk** [comment]
Oke

**Comment by kawaii-ghost** [comment]
Wei, kok diilangin lagi sih :'(.
